from model.baselines.bilateral_gaussian import BilateralGaussian
from model.baselines.canny_fill import CannyFill
from model.baselines.gaussian_threshold import GaussianThreshold
from model.baselines.otsu import Otsu
from model.baselines.unsupervised_clustering import UnsupervisedClustering